# Generated by Django 3.1.7 on 2021-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=60)),
                ('pub_date', models.DateField()),
                ('body_text', models.CharField(max_length=250)),
                ('blog_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
